version: "3.7"

x-common-props: &common-props
  build:
    context: ./
    target: base
  working_dir: /base
  volumes:
    - ./app:/base
    - node_modules:/base/node_modules

services: 
  yarn:
    <<: *common-props
    entrypoint: yarn
  dev:
    <<: *common-props
    ports: 
      - "5000:5000"
    command: yarn dev
volumes:
  node_modules: